services:
  hlc20-mqtt:
    image: ghcr.io/donmikele75/hlc20-mqtt:latest
    container_name: hlc20-mqtt
    restart: unless-stopped
    hostname: hlc20-mqtt
    volumes:
      - ./data:/app/data
    environment:
      TZ: "Europe/Berlin"
      SERIAL_HOST: "10.1.1.57"
      SERIAL_PORT: "9101"
      MQTT_HOST: "mqtt.int.wagner.tc"
      MQTT_PORT: "1883"
      MQTT_USER: "mqtt"
      MQTT_PASSWORD: "1mages+Words"
      POLL_INTERVAL: "60"
      DEVICE_TOPIC: "hlc20"
      DISCOVERY_PREFIX: "homeassistant"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 10.1.1.1
    networks:
      lan:
        ipv4_address: 10.1.1.215
        mac_address: 6C-1F-F7-E3-F6-EC

networks:
    lan:
        name: lan
        external: true
